<template>
  <div class="wizard-page">
    <!-- Header -->
    <header class="page-header">
      <div class="header-content">
        <div class="logo-area" @click="router.push('/drama')">
          <span class="logo-icon">&#127916;</span>
          <h1 class="logo">AI 剧本引导</h1>
        </div>
        <div class="header-right">
          <span v-if="dramaStore.currentProject" class="project-title-tag">
            {{ dramaStore.currentProject.title }}
          </span>
          <el-button text @click="router.push('/drama')">
            <el-icon><ArrowLeft /></el-icon> 返回列表
          </el-button>
        </div>
      </div>
    </header>

    <!-- Steps bar -->
    <div class="steps-container">
      <el-steps :active="wizardStepIndex" align-center>
        <el-step title="AI 问答" description="完善创意" />
        <el-step title="生成大纲" description="确认结构" />
        <el-step title="开始创作" description="进入工作台" />
      </el-steps>
    </div>

    <!-- Main content -->
    <div class="wizard-main">

      <!-- Step 0: Chat -->
      <template v-if="wizardStepIndex === 0">
        <div class="chat-container">
          <WizardChat
            v-if="!pageLoading"
            :project-id="projectId"
            :session="dramaStore.session"
            @outline-ready="handleOutlineReady"
          />
          <div v-else class="loading-area">
            <el-skeleton :rows="5" animated />
          </div>
        </div>

        <div class="wizard-footer">
          <el-button
            text
            :loading="skipping"
            @click="handleSkip"
            class="skip-btn"
          >
            跳过问答，直接生成大纲
          </el-button>
        </div>
      </template>

      <!-- Step 1: Outline review -->
      <template v-else-if="wizardStepIndex === 1">
        <div class="outline-review">
          <div class="outline-header">
            <h3 class="outline-title">剧本大纲</h3>
            <p class="outline-subtitle">请检查 AI 生成的大纲，可以在下方编辑后确认</p>
          </div>

          <div class="outline-tree-wrapper">
            <ScriptOutlineTree
              :nodes="dramaStore.nodes"
              :script-type="dramaStore.currentProject?.script_type || 'dynamic'"
              :current-node-id="null"
              @select-node="() => {}"
              @add-node="() => {}"
              @delete-node="handleDeleteOutlineNode"
              @rename-node="handleRenameOutlineNode"
            />
          </div>

          <div class="outline-actions">
            <el-button @click="wizardStepIndex = 0">重新问答</el-button>
            <el-button
              type="primary"
              size="large"
              :loading="confirming"
              @click="handleConfirmOutline"
              round
            >
              确认大纲，开始创作
            </el-button>
          </div>
        </div>
      </template>

    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { ArrowLeft } from '@element-plus/icons-vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { useDramaStore } from '@/stores/drama'
import { skipToOutline } from '@/api/drama'
import WizardChat from '@/components/drama/WizardChat.vue'
import ScriptOutlineTree from '@/components/drama/ScriptOutlineTree.vue'

const route = useRoute()
const router = useRouter()
const dramaStore = useDramaStore()

const projectId = computed(() => Number(route.params.id))
const pageLoading = ref(true)
const skipping = ref(false)
const confirming = ref(false)
const wizardStepIndex = ref(0)

async function handleOutlineReady() {
  // Load nodes generated by outline
  await dramaStore.fetchNodes(projectId.value)
  if (dramaStore.nodes.length) {
    wizardStepIndex.value = 1
  }
}

async function handleSkip() {
  try {
    await ElMessageBox.confirm(
      '跳过 AI 问答将直接根据你的故事创意生成大纲，确认继续？',
      '跳过问答',
      { confirmButtonText: '确认跳过', cancelButtonText: '取消', type: 'info' },
    )
  } catch {
    return
  }

  skipping.value = true
  try {
    await skipToOutline(projectId.value)
    await dramaStore.fetchNodes(projectId.value)
    if (dramaStore.nodes.length) {
      wizardStepIndex.value = 1
    } else {
      ElMessage.warning('大纲生成中，请稍后刷新')
    }
  } catch {
    ElMessage.error('跳过失败，请重试')
  } finally {
    skipping.value = false
  }
}

async function handleConfirmOutline() {
  confirming.value = true
  try {
    await dramaStore.confirmProjectOutline(projectId.value)
    ElMessage.success('大纲已确认！正在跳转工作台...')
    setTimeout(() => {
      router.push(`/drama/workbench/${projectId.value}`)
    }, 800)
  } catch {
    ElMessage.error('确认失败，请重试')
  } finally {
    confirming.value = false
  }
}

async function handleDeleteOutlineNode(nodeId: number) {
  try {
    await ElMessageBox.confirm('确定删除此节点？', '删除确认', {
      type: 'warning',
      confirmButtonText: '删除',
      cancelButtonText: '取消',
    })
    await dramaStore.removeNode(projectId.value, nodeId)
  } catch {
    // cancelled
  }
}

async function handleRenameOutlineNode(nodeId: number) {
  const node = dramaStore.nodes.find(n => n.id === nodeId)
  if (!node) return
  try {
    const { value } = await ElMessageBox.prompt('输入新名称', '重命名', {
      inputValue: node.title || '',
      confirmButtonText: '确认',
      cancelButtonText: '取消',
    })
    if (value?.trim()) {
      await dramaStore.editNode(projectId.value, nodeId, { title: value.trim() })
    }
  } catch {
    // cancelled
  }
}

onMounted(async () => {
  pageLoading.value = true
  try {
    await Promise.all([
      dramaStore.fetchProject(projectId.value),
      dramaStore.fetchSession(projectId.value),
      dramaStore.fetchNodes(projectId.value),
    ])

    // If nodes already exist, skip to outline review
    if (dramaStore.nodes.length && dramaStore.currentProject?.status !== 'drafting') {
      wizardStepIndex.value = 1
    }
  } catch {
    ElMessage.error('加载失败')
  } finally {
    pageLoading.value = false
  }
})
</script>

<style scoped>
.wizard-page {
  min-height: 100vh;
  background-color: #F0EFEC;
  display: flex;
  flex-direction: column;
}

.page-header {
  background-color: white;
  border-bottom: 1px solid #E0DFDC;
  padding: 0 32px;
  height: 64px;
  display: flex;
  align-items: center;
  flex-shrink: 0;
  box-shadow: 0 1px 3px rgba(44, 44, 44, 0.03);
}

.header-content {
  width: 100%;
  max-width: 1000px;
  margin: 0 auto;
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.header-right {
  display: flex;
  align-items: center;
  gap: 12px;
}

.logo-area {
  display: flex;
  align-items: center;
  gap: 8px;
  cursor: pointer;
}

.logo-icon { font-size: 22px; }

.logo {
  font-size: 20px;
  font-weight: 700;
  background: linear-gradient(135deg, #6B7B8D 0%, #5A6B7A 100%);
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  background-clip: text;
  font-family: 'Noto Serif SC', serif;
  margin: 0;
}

.project-title-tag {
  font-size: 13px;
  color: #7A7A7A;
  background: #F0EFEC;
  padding: 4px 12px;
  border-radius: 12px;
  border: 1px solid #E0DFDC;
}

.steps-container {
  max-width: 600px;
  margin: 0 auto;
  padding: 24px 32px 0;
  flex-shrink: 0;
}

.wizard-main {
  flex: 1;
  display: flex;
  flex-direction: column;
  max-width: 800px;
  width: 100%;
  margin: 0 auto;
  padding: 24px 32px 0;
  min-height: 0;
}

.chat-container {
  flex: 1;
  background: white;
  border-radius: 16px;
  border: 1px solid #E0DFDC;
  overflow: hidden;
  min-height: 480px;
  display: flex;
  flex-direction: column;
}

.loading-area {
  padding: 32px;
  flex: 1;
}

.wizard-footer {
  padding: 16px 0;
  text-align: center;
  flex-shrink: 0;
}

.skip-btn {
  color: #9E9E9E !important;
  font-size: 13px;
}

.skip-btn:hover {
  color: #6B7B8D !important;
}

/* Outline review */
.outline-review {
  display: flex;
  flex-direction: column;
  gap: 20px;
  padding-bottom: 32px;
}

.outline-header {
  text-align: center;
}

.outline-title {
  font-size: 22px;
  font-weight: 700;
  color: #2C2C2C;
  margin: 0 0 6px;
  font-family: 'Noto Serif SC', serif;
}

.outline-subtitle {
  font-size: 13px;
  color: #7A7A7A;
  margin: 0;
}

.outline-tree-wrapper {
  background: white;
  border: 1px solid #E0DFDC;
  border-radius: 16px;
  overflow: hidden;
  min-height: 300px;
  max-height: 480px;
}

.outline-actions {
  display: flex;
  justify-content: center;
  gap: 12px;
}

/* Steps overrides */
:deep(.el-step__title) { font-size: 13px; }
:deep(.el-step__description) { font-size: 11px; }
:deep(.el-step.is-process .el-step__title) { color: #6B7B8D; }
:deep(.el-step.is-process .el-step__icon) { border-color: #6B7B8D; color: #6B7B8D; }
:deep(.el-step.is-finish .el-step__title) { color: #6B7B8D; }
:deep(.el-step.is-finish .el-step__icon) { border-color: #6B7B8D; color: #6B7B8D; }

@media (max-width: 768px) {
  .wizard-main { padding: 16px; }
  .steps-container { padding: 16px 16px 0; }
  .page-header { padding: 0 16px; }
}
</style>
